const motivationalQuotes: string[] = [
  "Success is not the key to happiness. Happiness is the key to success.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you’re halfway there.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is not in what you have, but who you are.",
  "The future depends on what you do today.",
  "Dream big and dare to fail.",
  "The best way to predict the future is to create it.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t let yesterday take up too much of today.",
  "It does not matter how slowly you go as long as you do not stop.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only place where success comes before work is in the dictionary.",
  "Your only limit is your mind.",
  "Push yourself because no one else is going to do it for you.",
  "Sometimes later becomes never. Do it now.",
  "Great things never come from comfort zones.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Little things make big days.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "It’s going to be hard, but hard does not mean impossible.",
];

export default motivationalQuotes;
